### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by nicholasprayogo** [sanketkshah/NeurADP-for-Ride-Pooling#1]
Hi Sanket and team,

Hope all is well! I read your recent paper on NeurADP for RMP and I find that your implementation is really interesting; both the code and paper seem to be really well-written and informative so thank you for that! 

I'm trying to replicate your NeurADP implementation, however I think the missing link is the "data" directory that was not pushed to the repo, which I'm guessing is due to the file size limit on Github. May I know if I can request access to this data so that I can replicate your implementation, or if that's not possible, may I know how your team preprocessed the raw data provided by NY TLC? 

I'm a big fan of your work (I lived in Singapore for a few years before and am really glad such great paper came out of SMU!) and am really excited to see how it all works with the taxicab data. 

Thank you!
Nicholas

**Comment by sanketkshah** [comment]
Hi Nicholas, Just sent you an email!

For anyone else who's reading this, we couldn’t put the data files on GitHub because of licensing issues (they’re derivatives of existing open-source projects). However, if you get in touch with us over email (sanketkshah@gmail.com), we'll be happy to share the pre-processed data and pre-trained models.

**Comment by nicholasprayogo** [comment]
Hi Shah, 

Thank you very much!

**Comment by nicholasprayogo** [comment]
Hi Shah, 

Thank you very much!
